/*
 * RenderControl.java
 *
 * Created on May 7, 2006, 6:25 PM
 */
package net.javanetwork.xml.fop.view;

import java.io.File;
import javax.swing.SwingWorker;
import net.javanetwork.xml.fop.Controller;

/**
 *
 * @author John Yeary <jyeary@javanetwork.net>
 * @author John Yeary <jyeary@bluelotussoftware.com>
 * @version 1.1
 */
public class RenderControl extends javax.swing.JFrame {

    private static final long serialVersionUID = -5198288041461209978L;

    private final Controller ctl;

    /**
     * Creates new form RenderControl
     */
    public RenderControl() {
        initComponents();
        ctl = new Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_fo = new javax.swing.JTextField();
        jTextField_xslt = new javax.swing.JTextField();
        jTextField_xml = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonRender = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Render Control");

        jLabel1.setText("FO File:");

        jLabel2.setText("XSLT File:");

        jLabel3.setText("XML File:");

        jLabel4.setText("Output Format");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AWT", "PDF" }));

        jButtonRender.setText("Render");
        jButtonRender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenderActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel2)
                                    .add(jLabel1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextField_xml, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .add(jTextField_xslt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .add(jTextField_fo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(jButtonRender)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonCancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField_fo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField_xslt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField_xml, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 121, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonRender)
                    .add(jButtonCancel)
                    .add(jButtonExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenderActionPerformed

        String option = (String) jComboBox1.getSelectedItem();
        System.out.println(option);
        String foName = jTextField_fo.getText();
        String xslName = jTextField_xml.getText();
        String xmlName = jTextField_xml.getText();

        if (foName == null || foName.isEmpty()) {
            System.out.println("FO Name was empty");
        } else {
            ctl.setFoFile(new File(foName));
        }

        if (xslName == null || xslName.isEmpty() || xmlName == null || xmlName.isEmpty()) {
            System.out.println("The XSL and XML file names must be provided.");
        } else {
            ctl.setXsltFile(new File(jTextField_xslt.getText()));
            ctl.setXmlFile(new File(jTextField_xml.getText()));

            SwingWorker worker = null;

            switch (option) {
                case "AWT": {
                    worker = new SwingWorker() {
                        @Override
                        protected Object doInBackground() throws Exception {
                            ctl.viewFO();
                            return null;
                        }
                    };
                    break;
                }
                case "PDF": {
                    worker = new SwingWorker() {
                        @Override
                        protected Object doInBackground() throws Exception {
                            ctl.convertToPDF();
                            return null;
                        }
                    };
                    break;
                }
                default: {
                    worker = new SwingWorker() {
                        @Override
                        protected Object doInBackground() throws Exception {
                            return null;
                        }
                    };
                }
            }

            worker.execute();

            jButtonRender.setEnabled(false);
            jButtonCancel.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonRenderActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RenderControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRender;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField_fo;
    private javax.swing.JTextField jTextField_xml;
    private javax.swing.JTextField jTextField_xslt;
    // End of variables declaration//GEN-END:variables

}
